- name: Get TSO netstat home output from a z/OS LPAR
  hosts: all
  gather_facts: false
  collections:
    - ibm.ibm_zos_core

  tasks:
    - name: netstat home
      zos_operator:
        cmd: 'D TCPIP,,N,HOME'
        wait_time: 10
      register: netstat_home

    - name: Show NETSTAT HOME output
      debug:
        msg: "{{ netstat_home.content | default(['NO OUTPUT']) | join('\n') }}"
